# Generated by Django 4.2.16 on 2024-11-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('senderContent', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mail_sent_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('mail_messageId', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Email_Content',
            },
        ),
        migrations.CreateModel(
            name='Manual_Email',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manual_response', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('email_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.email_content')),
            ],
            options={
                'db_table': 'Manual_Email',
            },
        ),
    ]
